### ISSUE TITLE
broccoli builds fail in v 1.0.1

### ISSUE THREAD

**Issue by Datamance** [sass-eyeglass/ember-cli-eyeglass#13]
Hi there,

Just tried to update to ember-cli-eyeglass 1.0.1, and broccoli builds now fail starting at `Object.registry.add.toTree` in `node_modules/ember-cli-eyeglass/index.js` with a TypeError ("undefined is not a function.")

I can provide the full stacktrace if you need it.

**Comment by chriseppstein** [comment]
this should be working in later releases.
